---
title: 'Chapter 3: Compare means'
author: "Khia A. Johnson"
date: "7/23/2021"
output: html_document
---

```{r}
library(data.table)
library(tidyverse)
library(ggthemes)
library(lsr)
library(broom)
library(ggdist)

sessionInfo()
```

visualization defaults
```{r}
theme_set(theme_clean() + theme(
      legend.title = element_blank(),
      legend.text = element_text(size=6),
      legend.position = 'bottom',
      axis.title.x = element_text(size = 10, face='bold'),
      axis.title.y = element_text(size = 10, face='bold'),
      strip.text = element_text(size=10, face='bold'),
      plot.background = element_blank()
    ))
```


```{r}
df <- fread('../data/spice_voicesauce_processed.csv', sep = ',') 
```

Get correlation for F4 and FD
```{r}
fd <- df %>%
    select(F1:F4) %>%
    mutate(FD = ((F4-F3) + (F3-F2) + (F2-F1) )/3)
```


```{r}
cor.test(x = fd$F4, y= fd$FD, method = 'pearson')
```


## Visualize

Pivot longer to prep for getting t-test and cohen's d results // data viz
```{r}
long_df <- df %>%
  select(Talker, Language, F0:SHR_sd) %>%
  pivot_longer(F0:SHR_sd, names_to = 'Variable', values_to = 'Value')
```

```{r fig.width=5, fig.height=6.5}
long_df %>%
    filter(str_detect(Variable, 'sd', negate=TRUE)) %>%
  select(Talker, Language, Variable, Value) %>%
  ggplot(aes(x=Value, color=Language)) +
    geom_density() +
    scale_color_viridis_d(option='magma', begin = 0.75, end = 0)+
    facet_wrap(~Variable, scales = 'free', ncol = 3) +
    ylab('Density') +
    xlab('')

#ggsave('../../../text/figures/ch3_allmeasuresdensity_5in.png', width = 5, height = 6.5)

```

```{r fig.width=10, fig.height=6.5}
df %>%
  select(Talker, Language, F2) %>%
  left_join(f2d, by='Talker') %>%
  mutate(Difference = Difference>0) %>%
  ggplot(aes(x=F2, color=Language)) +
    geom_density() +
    scale_color_viridis_d(option='magma', begin = 0.75, end = 0)+
    facet_wrap(~Talker, ncol = 8) +
    ylab('Density') +
    xlab('')
```



```{r}
f2d <- cohensd %>%
    filter(Variable=='F2') %>%
    select(Talker, CohenD, Difference)
```


## T-tests galore
Do all the t-tests and cohen's d calculations
```{r}
# ttest_results <- long_df %>%
#   group_by(Talker, Variable) %>%
#   summarise(
#     cohen_d = cohensD(Value ~ Language, method='pooled'),
#     t_test = list(t.test(Value ~ Language,  var.equal = TRUE, conf.level = 0.95))
#     ) %>%
#   mutate(tidied=map(t_test,tidy)) %>%
#   unnest(tidied) %>%
#   select(Talker:cohen_d, estimate1:conf.high)

# fwrite(ttest_results,'../data/spice_voicesauce_ttests.csv')
ttest_results <- fread('../data/spice_voicesauce_ttests.csv')

```


Display the non-trivial comparisons
```{r fig.width=6, fig.height=12}
cohensd <- ttest_results %>%
  mutate(Difference = estimate1-estimate2,
         Significant = p.value < 0.01,
         CohenD = if_else(cohen_d<0.2, 'Trivial', 
                          if_else(cohen_d<0.5, 'Small', 
                                  if_else(cohen_d<0.8, 'Medium', 'Large')))
         ) %>%
  
  select(Talker, Variable, Difference, Significant, cohen_d, CohenD)
```

```{r}
cohensd %>%
  filter(CohenD != 'Trivial') %>%
  group_by(Talker) %>%
  summarise(n=n()) %>%
  ggplot(aes(x=n)) +
  geom_histogram(binwidth = 1, color='white', fill='black') +
  scale_x_continuous(limits = c(0,13), breaks = c(0,1,2,3,4,5,6,7,8,9,10,11,12) ) +
  ylab('Count') +
  xlab('Number of non-trivial comparisons')

#ggsave('../../../text/figures/ch3_nontrivial_counts_by_talker_5in.png', width = 5, height = 2.5)

```


Counts by Cohen's d brackets for table
```{r}
cohensd %>%
  mutate(positive = Difference>0) %>%
  group_by(Variable, positive, CohenD) %>%
  summarise(n = n()) %>%
  pivot_wider(names_from = c('positive','CohenD'), values_from = n) %>%
  select(Variable, FALSE_Small, FALSE_Medium, TRUE_Small, TRUE_Medium)
```

Energy: 10 neg, 7pos

## Data visualization
```{r fig.width=5.5, fig.height=7}
long_pointinterval <- long_df %>%
  group_by(Talker, Language, Variable) %>%
  summarise(m = mean(Value), 
    q025 = quantile(Value, 0.025), 
    q25 = quantile(Value, 0.25), 
    q75= quantile(Value, 0.75), 
    q975 = quantile(Value, 0.975)
    ) %>%
  left_join(cohensd, by=c('Talker','Variable'))
```

```{r}
plot_dist_cohen <-function(var, xlabel_text='!!!', cohensd_position=0) {
  p <- long_pointinterval %>%
    filter(Variable==var) %>%
    select(Talker, Language, Variable, m, q025, q25, q75, q975, cohen_d, CohenD) %>%
    ggplot(aes(y=Talker, color=Language)) +
      geom_linerange(aes(xmin=q025, xmax=q975), size=0.5, alpha=0.5, position = position_dodge(width = 0.7)) +
      geom_pointrange(aes(x = m, xmin=q25, xmax=q75), size=0.5, position = position_dodge(width = 0.7), shape=18) +
      geom_label(size =2.25, aes(fill=CohenD,x=cohensd_position, label=round(cohen_d,2)))+
      scale_color_viridis_d(option='magma', begin = 0.75, end = 0) +
      scale_fill_viridis_d(option='magma', begin = 0.5, end = 1) +
      scale_y_discrete(limits=rev) +
      xlab(xlabel_text) +
      theme(legend.position = 'right')
  return(p)
}
```

```{r fig.width=5, fig.height=6.5}
# plot_dist_cohen('F0', 'F0 (Hz)', 425)
# plot_dist_cohen('H1H2c', 'H1*-H2* (dB)', 16)
# 
# plot_dist_cohen('F1', 'F1 (Hz)', 1150)
# plot_dist_cohen('F2', 'F2 (Hz)', 3000)
# plot_dist_cohen('F3', 'F3 (Hz)', 4100)
# plot_dist_cohen('F4', 'F4 (Hz)', 4800)
# plot_dist_cohen('H2H4c', 'H2*-H4* (dB)', 28)
# plot_dist_cohen('H42Kc', 'H4*-H2kHz* (dB)', 28)
# plot_dist_cohen('H2KH5Kc', 'H2kHz*-H5kHz* (dB)', 70)
# plot_dist_cohen('CPP', 'CPP (dB)', 32)
# plot_dist_cohen('Energy', 'Energy (dB)', 10)
# plot_dist_cohen('SHR', 'SHR', 1.05)
```



```{r fig.height=6.5, fig.width=5}
long_pointinterval %>%
  mutate(
    CohenD = as_factor(CohenD),
    Variable = str_replace(Variable, '_sd', ' s.d.'),
    Variable = str_replace(Variable, 'H1H2c', 'H1*-H2*'),
    Variable = str_replace(Variable, 'H2H4c', 'H2*-H4*'),
    Variable = str_replace(Variable, 'H42Kc', 'H4*-H2kHz*'),
    Variable = str_replace(Variable, 'H2KH5Kc', 'H2kHz-H5kHz*')
  ) %>%
  filter(str_detect(Variable, 's.d.', negate=TRUE)) %>%
  ggplot(aes(x=cohen_d, y=Difference, color=CohenD, shape=CohenD)) + 
  geom_point() +
  geom_hline(aes(yintercept = 0))+
  scale_color_viridis_d(option='magma', begin = 0.9, end=0) +
  facet_wrap(~Variable, scales = 'free', ncol=3)

ggsave('../../../text/figures/ch3_cohend_part1_5in.png', width = 5, height = 6.5)
```


```{r fig.height=6.5, fig.width=5}
long_pointinterval %>%
  mutate(
    CohenD = as_factor(CohenD),
    Variable = str_replace(Variable, '_sd', ' s.d.'),
    Variable = str_replace(Variable, 'H1H2c', 'H1*-H2*'),
    Variable = str_replace(Variable, 'H2H4c', 'H2*-H4*'),
    Variable = str_replace(Variable, 'H42Kc', 'H4*-H2kHz*'),
    Variable = str_replace(Variable, 'H2KH5Kc', 'H2kHz-H5kHz*')
  ) %>%
  filter(str_detect(Variable, 's.d.', negate=FALSE)) %>%
  ggplot(aes(x=cohen_d, y=Difference, color=CohenD, shape=CohenD)) + 
  geom_point() +
  geom_hline(aes(yintercept = 0))+
  scale_color_viridis_d(option='magma', begin = 0.9, end=0.45) +
  facet_wrap(~Variable, scales = 'free', ncol=3)
ggsave('../../../text/figures/ch3_cohend_part2_5in.png', width = 5, height = 6.5)
```


